### PR TITLE
Add tutorials for go-fuzz and cargo-fuzz(rust)

### PR DESCRIPTION
**Pull request by yevgenypats**
Hey team,

I've added two short tutorials for go-fuzz and cargo-fuzz(rust) that I wrote. 

Cheers,
Yevgeny

### CODE REVIEW

**Comment by yevgenypats** [comment]
I don't have a markdown version but I can transform if needed. (I prefer it to be a link to the site if possible)

**Comment by Dor1s** [comment]
External sites live their own lives and may mutate / disappear / etc over time, so it's better to keep all the necessary files right here in the repo. For example, we have https://github.com/google/fuzzing/blob/master/docs/afl-based-fuzzers-overview.md instead of https://habr.com/en/company/dsec/blog/449134/ or even slides in PDF instead of a link to either Google Slides or Slideshare.

**Comment by yevgenypats** [comment]
Hey @Dor1s, I hope we won't disappear soon:)

copy pasting my blogs without reference on Google wiki/repo feels a bit like I won't get the right credit and just improve Google wiki. I would appreciate if it will be possible to have a link to the source blog. If this won't work let me know and I'll think if there is another solution that can work for both of us...

Cheers,
Yevgeny

**Comment by yevgenypats** [comment]
friendly ping to check the status on that.

**Comment by Dor1s** [comment]
Sorry, in the current form the PR doesn't fit the format of the repo. Let me close it for now.

There are other projects that work more like a collection of links, e.g. https://github.com/secfigo/Awesome-Fuzzing, make sure to link your articles there!

**Comment by yevgenypats** [comment]
sure, will put the links there:)

**Pull request closed without merging**
